config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'} 
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "events#index"
  get  "login", to: "application#login"
  get  "signin", to: "application#signin"
  get  "productos", to: "application#productos"
  get  "nosotros", to: "application#nosotros"
  get  "cart", to: "application#cart"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates_presence_of :titulo, :descripcion;
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # obliga al usuario a iniciar sesion antes de entrar al inicio
  # before_action :authenticate_user!
    # GET /events/login
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :apellido, :username, :email, :password, :password_confirmation])
  end

  def login
    
  end
    # GET /events/signin
  def signin
  
  end

  def productos
  end

  def nosotros
  end

  def cart
  end

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end


  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:titulo, :descripcion, :fecha)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def new 
        super
    end
    
    def create
        super
        
    end

    def update
        super
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/saludo_helper.rb
module SaludoHelper
end

app/views/application/cart.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Video Vintage</title>


    <!-- Bootstrap core CSS -->
<link source="/app/assets/stylesheets/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      
    </style>
    <!-- Custom styles for this template -->
    <link source="/app/assets/stylesheets/product.scss" rel="stylesheet">
  </head>
  <body>
    <nav class="sticky-top py-1 navbar navbar-expand-lg navbar-light bg-light">
  <div class="container d-flex flex-column flex-md-row justify-content-between">
    <a class="py-2" href="#" aria-label="Product">
    <!--
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d=""/></svg>
    <img source="kino1.svg">
    -->
    <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="80pt" height="80pt" viewBox="0 0 675.000000 505.000000"
 preserveAspectRatio="xMidYMid meet">
<g transform="translate(0.000000,505.000000) scale(0.100000,-0.100000)"
fill="#000000" stroke="none">
<path d="M3250 4968 c-143 -32 -217 -73 -329 -185 -77 -78 -106 -114 -136
-175 -44 -89 -14 -73 -320 -173 -110 -35 -230 -75 -267 -87 l-67 -22 -81 38
c-77 37 -86 39 -208 43 -117 5 -133 3 -204 -20 -152 -51 -265 -160 -329 -318
-26 -64 -29 -82 -29 -189 0 -99 4 -127 25 -185 29 -80 105 -199 143 -222 15
-10 41 -28 57 -42 38 -30 150 -81 180 -81 12 0 27 -6 33 -12 15 -19 26 -115
14 -122 -18 -11 -116 -28 -163 -28 -45 0 -133 35 -172 70 -16 14 -19 14 -28 2
-10 -16 -9 -24 15 -165 9 -49 22 -125 28 -167 7 -42 17 -80 21 -85 5 -4 41 27
80 70 69 75 74 79 132 88 33 6 76 11 94 12 32 2 36 -1 44 -33 12 -47 41 -207
86 -476 5 -28 18 -68 29 -90 25 -49 101 -121 138 -130 37 -10 215 2 246 17 38
17 60 0 102 -80 20 -39 41 -73 46 -76 6 -3 10 -13 10 -21 0 -13 -109 -14 -845
-12 l-845 3 2 -875 3 -875 2521 -3 2522 -2 6 22 c3 13 6 407 6 876 l0 852
-1497 0 c-823 0 -1494 3 -1491 6 5 5 185 41 248 50 24 3 108 18 285 49 44 8
132 24 195 35 183 33 284 52 337 64 53 12 55 17 83 205 5 36 14 69 19 74 4 4
33 12 62 17 219 36 264 60 318 167 22 45 29 149 12 182 -5 9 -11 44 -13 76
l-3 60 45 7 c215 35 215 35 375 -6 33 -8 98 -24 145 -36 47 -12 110 -27 140
-35 30 -8 93 -24 140 -36 47 -12 103 -22 125 -23 l40 -1 -2 40 c-1 36 -10 88
-57 360 -8 44 -24 136 -36 205 -11 69 -28 161 -36 205 -8 44 -24 132 -35 195
-11 63 -22 130 -25 148 -11 62 -23 56 -331 -156 -323 -222 -337 -231 -394
-238 -30 -4 -61 -10 -69 -14 -8 -4 -43 -10 -76 -14 l-62 -7 -6 33 c-4 18 -11
60 -16 93 -15 92 -46 158 -92 196 -76 64 -80 70 -73 92 31 99 29 302 -4 397
-65 192 -180 326 -354 413 -144 72 -299 91 -457 55z m213 -99 c43 -22 97 -84
108 -123 14 -51 2 -65 -44 -48 -43 16 -201 16 -244 0 -28 -10 -36 -10 -49 4
-15 14 -14 19 4 59 33 74 94 116 170 118 18 1 43 -4 55 -10z m368 -214 c14 -8
40 -30 58 -50 28 -32 31 -42 31 -101 0 -51 -5 -72 -25 -104 -27 -42 -55 -63
-72 -52 -5 4 -13 27 -17 50 -9 61 -36 110 -97 177 -43 46 -51 60 -42 73 20 33
107 36 164 7z m-775 -125 c-30 -40 -49 -79 -57 -116 -7 -31 -18 -58 -25 -61
-23 -9 -54 17 -79 67 -28 56 -31 82 -11 99 20 16 167 70 193 71 21 0 20 -5
-21 -60z m-336 -110 c-12 -105 -3 -255 18 -316 33 -94 52 -137 78 -171 24 -32
31 -53 17 -53 -8 0 -125 -21 -263 -46 -176 -32 -202 -35 -207 -31 -2 3 -6 40
-7 84 -1 43 -10 105 -19 138 -21 71 -82 178 -126 219 -17 17 -31 35 -31 41 0
7 98 44 218 84 119 39 235 78 257 86 62 22 71 17 65 -35z m-830 -112 c19 -13
35 -28 37 -35 3 -8 -39 -26 -114 -50 -65 -20 -122 -38 -128 -38 -13 0 -7 43
12 78 33 65 130 87 193 45z m1979 -83 c32 -27 65 -101 59 -131 -3 -15 -21 -22
-88 -35 -47 -8 -86 -12 -88 -7 -2 4 5 23 16 40 11 18 28 61 38 96 9 34 21 62
25 62 4 0 21 -11 38 -25z m-875 -24 c9 -56 49 -131 102 -190 60 -67 52 -81
-51 -81 -65 0 -77 3 -106 27 -37 31 -69 95 -69 138 0 41 33 109 61 129 39 27
56 21 63 -23z m-1414 -36 c17 -9 30 -18 30 -21 0 -3 -20 -29 -45 -57 -29 -34
-51 -72 -62 -107 -9 -30 -20 -59 -23 -63 -4 -4 -21 8 -39 28 -27 31 -31 43
-31 95 0 70 22 101 85 124 53 18 52 18 85 1z m543 2 c113 -40 139 -155 54
-236 -14 -12 -30 -20 -35 -17 -5 3 -12 28 -16 56 -6 44 -15 60 -61 110 -30 33
-55 62 -55 65 0 4 57 32 70 34 3 0 22 -5 43 -12z m-633 -349 c0 -37 48 -130
88 -170 28 -30 33 -41 24 -50 -15 -15 -111 -15 -140 1 -33 17 -52 64 -52 125
0 44 5 60 26 85 30 37 54 40 54 9z m-450 -1819 l0 -69 -85 0 -85 0 0 68 c0 38
2 71 4 73 2 2 41 3 85 1 l81 -4 0 -69z m580 0 l0 -69 -85 0 -85 0 0 70 0 69
78 3 c42 2 80 2 85 0 4 -2 7 -34 7 -73z m290 0 l0 -69 -85 0 -85 0 0 68 c0 38
2 71 4 73 2 2 41 3 85 1 l81 -4 0 -69z m290 0 l0 -69 -85 0 -85 0 0 70 0 69
78 3 c42 2 80 2 85 0 4 -2 7 -34 7 -73z m1740 0 l0 -70 -82 3 -83 3 0 65 0 65
75 5 c41 3 78 4 83 2 4 -2 7 -35 7 -73z m298 3 l-3 -67 -87 -3 -88 -3 0 69 c0
38 2 71 4 73 2 2 43 3 91 1 l86 -3 -3 -67z m577 -2 l0 -65 -84 0 -85 0 3 65
c1 35 4 67 6 70 2 3 38 3 82 0 l78 -5 0 -65z m-3485 0 l0 -70 -85 0 -85 0 0
70 0 70 85 0 85 0 0 -70z m1165 0 l0 -65 -87 -3 -88 -3 0 71 0 71 88 -3 87 -3
0 -65z m285 0 l0 -71 -82 3 -83 3 -3 68 -3 67 86 0 85 0 0 -70z m295 0 l0 -65
-85 0 -85 0 -3 68 -3 68 88 -3 88 -3 0 -65z m285 0 l0 -71 -82 3 -83 3 -3 68
-3 67 86 0 85 0 0 -70z m295 0 l0 -65 -87 -3 -88 -3 0 71 0 71 88 -3 87 -3 0
-65z m873 3 l-3 -68 -85 0 -85 0 -3 54 c-5 81 -5 81 93 81 l86 0 -3 -67z m582
-3 l0 -71 -87 3 -88 3 -3 68 -3 67 91 0 90 0 0 -70z m285 0 l0 -65 -82 -3 -83
-3 0 71 0 71 83 -3 82 -3 0 -65z m295 0 l0 -71 -87 3 -88 3 -3 54 c-5 81 -5
81 93 81 l85 0 0 -70z m-3805 -745 l0 -600 -505 0 -505 0 -3 590 c-1 325 0
596 3 603 3 10 110 12 507 10 l503 -3 0 -600z m1273 -3 l2 -602 -512 2 -513 3
-3 590 c-1 325 0 596 3 603 3 10 111 12 512 10 l508 -3 3 -603z m1257 3 l0
-600 -505 0 -505 0 -3 590 c-1 325 0 596 3 603 3 10 110 12 507 10 l503 -3 0
-600z m1273 -3 l2 -602 -512 2 -513 3 -3 590 c-1 325 0 596 3 603 3 10 111 12
512 10 l508 -3 3 -603z m-4648 -752 l0 -70 -85 0 -85 0 0 70 0 70 85 0 85 0 0
-70z m290 0 l0 -70 -85 0 -85 0 0 70 0 70 85 0 85 0 0 -70z m290 0 l0 -70 -85
0 -85 0 0 70 0 70 85 0 85 0 0 -70z m290 0 l0 -70 -85 0 -85 0 0 70 0 70 85 0
85 0 0 -70z m290 0 l0 -70 -85 0 -85 0 0 70 0 70 85 0 85 0 0 -70z m298 -2 l3
-68 -91 0 -90 0 0 70 0 71 88 -3 87 -3 3 -67z m282 2 l0 -70 -85 0 -85 0 0 70
0 70 85 0 85 0 0 -70z m298 -2 l3 -68 -91 0 -90 0 0 70 0 71 88 -3 87 -3 3
-67z m282 2 l0 -70 -85 0 -85 0 0 70 0 70 85 0 85 0 0 -70z m298 -2 l3 -68
-91 0 -90 0 0 70 0 71 88 -3 87 -3 3 -67z m282 2 l0 -70 -85 0 -85 0 0 63 c0
35 3 67 7 70 3 4 42 7 85 7 l78 0 0 -70z m298 -2 l3 -68 -91 0 -90 0 0 70 0
71 88 -3 87 -3 3 -67z m290 0 l3 -68 -91 0 -90 0 0 63 c0 35 3 67 7 71 4 4 43
5 88 4 l80 -3 3 -67z m290 0 l3 -68 -84 0 c-46 0 -86 2 -88 4 -2 2 -2 34 -1
71 l4 66 81 -3 82 -3 3 -67z m292 2 l0 -70 -90 0 -90 0 0 63 c0 35 3 67 7 70
3 4 44 7 90 7 l83 0 0 -70z m288 -2 l3 -68 -86 0 -85 0 0 70 0 71 83 -3 82 -3
3 -67z m292 2 l0 -70 -90 0 -90 0 0 63 c0 35 3 67 7 70 3 4 44 7 90 7 l83 0 0
-70z"/>
<path d="M1090 1250 l0 -400 90 0 90 0 1 163 c0 99 4 154 9 142 5 -11 21 -84
36 -162 l27 -143 93 0 c73 0 94 3 94 14 0 7 -20 104 -44 214 l-45 201 48 186
48 185 -92 0 -91 0 -40 -162 -39 -163 -3 163 -2 162 -90 0 -90 0 0 -400z"/>
<path d="M2490 1210 l0 -400 90 0 90 0 0 400 0 400 -90 0 -90 0 0 -400z"/>
<path d="M3680 1230 l0 -400 85 0 85 0 1 138 1 137 22 -110 c37 -185 22 -165
126 -165 l90 0 0 400 0 400 -90 0 -90 0 -1 -142 -1 -143 -24 120 c-13 66 -26
130 -29 143 -5 21 -11 22 -90 22 l-85 0 0 -400z"/>
<path d="M5034 1653 c-12 -2 -32 -15 -45 -29 l-24 -26 0 -339 0 -339 28 -27
27 -28 156 0 156 0 23 27 c34 39 37 78 33 403 -3 319 -5 326 -63 351 -33 13
-234 18 -291 7z m176 -393 l0 -240 -35 0 -35 0 0 240 0 240 35 0 35 0 0 -240z"/>
</g>
</svg>
    </a>
    <%= link_to 'Productos', 'productos', :class => "nav-link"%>
    <%= link_to 'Nosotros', 'nosotros', :class => "nav-link"%>
    <%= link_to 'Cart/Stock', 'cart', :class => "nav-link"%>
    
      <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
      En sesión:  <strong><%= current_user.nombre %></strong>.
      <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
      <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Ingresar", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>

  </div>
</nav>

<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="72pt" height="21pt" viewBox="0 0 725.000000 217.000000"
 preserveAspectRatio="xMidYMid meet">
<g transform="translate(0.000000,217.000000) scale(0.100000,-0.100000)"
fill="#000000" stroke="none">
<path d="M230 1090 l0 -630 3375 0 3375 0 0 630 0 630 -3375 0 -3375 0 0 -630z
m1320 -10 l0 -420 -635 0 -635 0 0 420 0 420 635 0 635 0 0 -420z m1348 -2 l2
-418 -635 0 -635 0 0 420 0 420 633 -2 632 -3 3 -417z m1342 2 l0 -420 -630 0
-630 0 0 420 0 420 630 0 630 0 0 -420z m1350 0 l0 -420 -635 0 -635 0 0 413
c0 228 3 417 7 420 3 4 289 7 635 7 l628 0 0 -420z m1350 0 l0 -420 -635 0
-635 0 0 413 c0 228 3 417 7 420 3 4 289 7 635 7 l628 0 0 -420z"/>
<path d="M510 1395 l0 -85 30 0 30 0 0 -230 0 -230 -30 0 c-30 0 -30 -1 -30
-55 l0 -55 140 0 140 0 0 55 c0 52 -1 55 -25 55 -25 0 -25 1 -25 85 l0 85 30
0 c27 0 33 -7 70 -80 45 -90 45 -90 25 -90 -12 0 -15 -13 -15 -55 l0 -55 145
0 145 0 0 55 0 55 -43 0 -42 0 -58 115 -57 115 57 115 58 115 42 0 43 0 0 85
0 85 -145 0 -145 0 0 -85 c0 -69 3 -85 15 -85 20 0 20 0 -25 -90 -37 -73 -43
-80 -70 -80 l-30 0 0 85 c0 84 0 85 25 85 25 0 25 1 25 85 l0 85 -140 0 -140
0 0 -85z"/>
<path d="M2030 1405 l0 -85 30 0 30 0 0 -230 0 -230 -30 0 -30 0 0 -85 0 -85
145 0 145 0 0 85 0 85 -30 0 -30 0 0 230 0 230 30 0 30 0 0 85 0 85 -145 0
-145 0 0 -85z"/>
<path d="M3230 1405 l0 -85 30 0 30 0 0 -230 0 -230 -30 0 -30 0 0 -85 0 -85
140 0 140 0 0 85 c0 84 0 85 -25 85 l-25 0 1 143 0 142 115 -227 114 -228 85
0 85 0 0 315 0 315 25 0 c25 0 25 1 25 85 l0 85 -140 0 -140 0 0 -85 0 -85 30
0 30 0 -1 -142 0 -143 -115 228 -114 227 -115 0 -115 0 0 -85z"/>
<path d="M4717 1422 l-57 -58 0 -284 0 -284 57 -58 57 -58 171 0 171 0 57 58
57 58 0 285 0 285 -58 57 -58 57 -170 0 -170 0 -57 -58z m316 -140 l27 -28 0
-174 0 -174 -27 -28 c-24 -25 -34 -28 -88 -28 -54 0 -64 3 -88 28 l-27 28 0
169 0 169 32 33 c29 30 38 33 88 33 49 0 60 -4 83 -28z"/>
<path d="M5962 933 l3 -138 224 -3 c173 -2 226 1 233 10 4 7 8 70 8 141 l0
127 -235 0 -236 0 3 -137z m406 10 c-38 -4 -38 -5 -38 -49 0 -44 0 -44 36 -44
21 0 33 -4 29 -10 -4 -6 -83 -10 -206 -10 -126 0 -199 4 -199 10 0 6 16 10 36
10 l35 0 -3 43 c-3 39 -5 42 -38 48 -19 4 60 6 175 6 116 0 193 -2 173 -4z"/>
<path d="M6070 895 l0 -45 126 0 125 0 -3 43 -3 42 -122 3 -123 3 0 -46z"/>
</g>
</svg>

      <small class="d-block mb-3 text-muted">&copy; 2020 Universidad Libre</small>
    </div>
    
    <div class="col-6 col-md">
      <h5>Acerca de</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Equipo</a></li>
        <li><a class="text-muted" href="#">Ubicación</a></li>
      </ul>
    </div>
  </div>
</footer>
</body>

</html>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.datetime_select :fecha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.titulo %></td>
        <td><%= event.descripcion %></td>
        <td><%= event.fecha %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @event.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @event.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @event.fecha %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  


    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>